<?php

namespace Tests\Feature\Public;

use App\Models\NewsPost;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class NewsShowTest extends TestCase
{
    use RefreshDatabase;

    public function test_published_news_shows_by_slug(): void
    {
        $post = NewsPost::create([
            'title' => 'Batch Opening for 2026',
            'slug' => 'batch-opening-2026',
            'body' => 'Full body content.',
            'is_published' => true,
            'published_at' => now(),
        ]);

        $response = $this->get(route('news.show', $post));
        $response->assertOk();
        $response->assertSee('Batch Opening for 2026');
    }

    public function test_unpublished_news_returns_404(): void
    {
        $post = NewsPost::create([
            'title' => 'Draft Article',
            'slug' => 'draft-article',
            'body' => 'Draft body.',
            'is_published' => false,
        ]);

        $this->get(route('news.show', $post))->assertNotFound();
    }

    public function test_id_based_url_returns_404_after_slug_binding_fix(): void
    {
        $post = NewsPost::create([
            'title' => 'Posted via id',
            'slug' => 'posted-via-id',
            'body' => 'Body.',
            'is_published' => true,
            'published_at' => now(),
        ]);

        // Before the fix, /news/{id} was generated by the index and
        // would 404 because the controller looked for slug = id. The
        // fix binds the route to slug, so numeric URLs continue to 404,
        // but the slug-based URL works.
        $this->get('/news/'.$post->id)->assertNotFound();
        $this->get(route('news.show', $post))->assertOk();
    }

    public function test_index_page_links_use_slugs_not_ids(): void
    {
        $post = NewsPost::create([
            'title' => 'Linked Article',
            'slug' => 'linked-article',
            'body' => 'Body.',
            'is_published' => true,
            'published_at' => now(),
        ]);

        $response = $this->get(route('news'));
        $response->assertOk();
        $response->assertSee('href="'.route('news.show', $post).'"', false);
        $response->assertDontSee('href="/news/'.$post->id.'"', false);
    }
}
